apiVersion: v2
name: Dev-va6
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.0.1"

# The dependencies section is used to define charts on which the service is dependent on
# In this section service should define the ethos k8s helm templates as a dependency 
dependencies:
  # Name of the chart being used as the dependency, its ethos-k8s-helm-templates for ethos provided service templates
- name: ethos-k8s-helm-templates
  # The version of the helm templates to be used. Note that the '^' prefix means that it will automatically fetch the latest major version '1'
  version: "^1.0.0"
  # The path to pull the depedency from.
  repository: "https://artifactory-uw2.adobeitc.com/artifactory/helm-ethos-k8s-helm-templates-release"
