# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Deployment Pipeline

on:
  push:
    paths-ignore:
      - 'k8s/**'
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

permissions:
  deployments: write
  contents: write
  statuses: write
  actions: write

jobs:
  build-and-push:
    name: 'Build and Push'
    uses: ./.github/workflows/build_and_push.yaml
    secrets: inherit
  
  deploy-on-dev:
    name: 'Deploy to Dev va6'
    uses: ./.github/workflows/deploy.yaml
    with:
      target-env: Dev
    secrets: inherit
    needs: 
      - build-and-push
      
  parallel-job-to-dev-deployment:
    environment: 'Deploy to Dev va7'
    runs-on: ubuntu-20.04
    needs:
      - build-and-push
    steps:
      - run: echo "I am just a test"
          
  manual-approval:
    environment: 'Approval needed for Prod'
    runs-on: ubuntu-20.04
    needs:
      - deploy-on-dev
      - parallel-job-to-dev-deployment
    steps:
      - run: echo "Approved to Prod"
      
  deploy-on-prod:
    name: 'Deploy to Prod'
    uses: ./.github/workflows/deploy.yaml
    with:
      target-env: Prod
    secrets: inherit
    needs: 
      - manual-approval
      
  exit-handler:
    name: 'Exit Handler'
    uses: ./.github/workflows/exit.yaml
    if: failure()
    
